---
version: "3"

env:
  VERSION:
    sh: git describe --tags --dirty --always | sed 's/^v//'
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
tasks:
  build:
    desc: Build binary
    cmds:
      - >
        go build
        -ldflags "-X main.version=$VERSION"
        -o dist/zabbix-vault-pki
        ./cmd/zabbix-vault-pki
  deb:
    deps:
      - build
    cmds:
      - rm -rf dist/deb
      - mkdir -p dist/deb/usr/bin/
      - mkdir -p dist/deb/etc/zabbix-vault-pki/
      - cp dist/zabbix-vault-pki dist/deb/usr/bin/
      - cp -r packaging/deb/DEBIAN dist/deb/
      - cp packaging/etc/config.hcl dist/deb/etc/zabbix-vault-pki/
      - sed -i "s/VERSION/${VERSION}/" dist/deb/DEBIAN/control
      - dpkg-deb --build --root-owner-group dist/deb dist/zabbix-vault-pki_${VERSION}_${GOARCH}.deb
  rpm:
    deps:
      - build
    cmds:
      - rm -rf dist/rpm
      - mkdir -p dist/rpm/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
      - cp packaging/rpm/zabbix-vault-pki.spec dist/rpm/SPECS/
      - cp dist/zabbix-vault-pki dist/rpm/SOURCES/
      - cp packaging/etc/config.hcl dist/rpm/SOURCES/
      - sed -i "s/VERSION/${VERSION}/" dist/rpm/SPECS/zabbix-vault-pki.spec
      - rpmbuild -bb --define "_topdir $(pwd)/dist/rpm" dist/rpm/SPECS/zabbix-vault-pki.spec
  lint:
    desc: Run linter
    cmds:
      - golangci-lint run --fix
